travis:
  secure:
    BINSTAR_TOKEN: XtFHx7sEfyjYWYge42/PFJWns/TE7t/WN2SophDfXkXXIBxGba80ix2B3O800boZKm5eJ2KMY7vKsGFNTCQDF+tlJKejbjGYtQreQIKz4Gdf/Hhfbvg616YjLeVAkvSijo5dZ/3mpDwGoCD6TYsx5x3dxq5RUzKbHePHKFL+GrE+hwlWHTLA0HSUpNN3mHxfwcZkqkRGG3XaHcDWZ3hmz9I+J3Qmtt6zptAMdfLCfFiFTd3sXzlsSjdgp764vj34qH9g78FBhCwViB7xOMppZ0G0IH0qEsGz4qt3lonPnzAl+7JJYqIyxeLFHva1ak27sZ1DQVm1+7c2BqnpiQCZWWfRcp5FQetMXZY+PC/rrq0csJXho4MgpxSAN12RYXMgfjerXES99iziaqdH4S33L9M8dmIedJpuOvysACwH+qJoZHFhGSIhkUxB4bpVoDTX3oaUx+Va4KUkIYZ3ndG3YRtZZBFU668NIdiRHIoNDNdN21Apd9b9aiZmOu20zO1WRapVpbd5NEG9Io2pwNqr0AOd6uAkKoMHJYM9veFXnwin6lpAejEbhXx1zs+2rG/7wDVqW4emac7qqM/VZffWRPaAmzuEpKbTYZXdzh6GSVY+mP3OursILwJ2TIGF3ItJ/DpXPyI2f0OlnfBZ5Q1BTX/wKLUi7MJKl6FHI8yDZRs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
