travis:
  secure:
    BINSTAR_TOKEN: Ka5NqPiRMZ+SkAQg1kJflhmV7CjDLjLiSbN2Q6a2kFatN7iVJ3uklrG8Z8HAt5szvNRyi5rAccw0AJEQvd1mdDSHKGNKPrDl51miKWqdjy9keXA56O4P0Fm0atFJcQf8enCpBYghwxE2hWXNLExiFLoR+2UBftcS/MPNFY844ko0zfo+bZyUsbUv7QL5dCf7/FYA+T4AW+2Tg42Y+EaVECapGitOXVsB/NnhsaEwjOwWBF5VJ6LOUiuy+dA2q+rWm0+kQSI5ml1MSyKqP9smFw/2Gnf8c5AhuSxrne5ABl3kir1z5jzu71aW4fxp1DVVktPjr2xy/5gx/cIr7f8ZMPy7I06o0bvyGRHxUe5UOtTswXhD2Wv6c+ZovbkxRe+l/gelYOFmdzsMgkY8F+x0Wnvi92u3r1q4Qi3FrHPYRVjcEqTE/usf3ci0Rdam+eWp4frXmYsC0CBdO2QmZI8OIv29awaEued84/7LRfSJlH7uaHGmFQQHh1kqe+eHOh6LN9a82F890V9zsL+8P44p6+EM5IN2k2NvUjDBuNw7ljTv6q9eMprpOmDlFxIuat0B3XEnwVIH5+TM+tDV0uxbbGqLEhD7Xs+Fz6ZXbjuSiOrFI0YakI4BwwicdkdaRr4+09TVgfw4TerTyAEH/iEjkOr8Tp9so7UTkpirO47U0Ws=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
